debug:
  enabled: false
# etcd:
#   enabled: true
#   endpoints:
#     - 'http://kvstore:2379'
# identityAllocationMode: kvstore
prometheus:
  enabled: true
hubble:
  relay:
    enabled: true
  ui:
    enabled: true
dnsProxy:
  endpointMaxIpPerHostname: 512
  proxyResponseMaxDelay: 2s
  minTtl: 300
  dnsRejectResponseCode: nameError
image:
  override: "localhost:5000/cilium/cilium-dev:local"
  pullPolicy: Never
operator:
  image:
    override: "localhost:5000/cilium/operator-generic:local"
    pullPolicy: Never
    suffix: ""
  nodeSelector:
    kubernetes.io/os: linux
    kubernetes.io/hostname: kind-worker
ipam:
  mode: kubernetes
ipv6:
  enabled: false
ipv4:
  enabled: true
bpf:
  monitorAggregation: none
livenessProbe:
  failureThreshold: 9999
readinessProbe:
  failureThreshold: 9999
startupProbe:
  failureThreshold: 9999
